<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Sxpe.Games.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sxpe.Core\Sxpe.Core.csproj" />
    <ProjectReference Include="..\..\src\Sxpe.Games.Abstractions\Sxpe.Games.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Sxpe.Games.Sims3\Sxpe.Games.Sims3.csproj" />
  </ItemGroup>
</Project>
